config/routes.rb
Rails.application.routes.draw do
  resources :sales_pages
  resources :fans

  devise_for :admins
  resources :bands do
    resources :fans
    resources :pages, controller: 'bands/pages'
  end

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/confirm'
  get 'static_pages/thanks'
  get 'static_pages/free_download'
  get 'static_pages/youareahero'

   get '/confirm', to: "static_pages#confirm" 
   get '/thanks', to: "static_pages#thanks"
   get '/youareahero', to: "static_pages#youareahero", name: :youareahero
  resources :pages

  
  get '/music', to: "sales_pages#show"
  post '/music', to: "sales_pages#done"
  get '/:id', to: "pages#show"
 

end

app/views/pages/_form.html.erb
<% content_for :head do %>
 <script type="text/javascript">
   $(document).on('ready page:change', function () {
 
      $("#page_fb_headline").keyup(function() {
        var headline_counter = $("#headline_counter");
        var charsRemaining = 25 - $(this).val().length;
        headline_counter.text(charsRemaining);
        headline_counter.css('color', (charsRemaining < 0) ? 'red' : 'black');
      });

      $("#page_fb_text").keyup(function() {
        var text_counter = $("#text_counter");
        var charsRemaining = 90 - $(this).val().length;
        text_counter.text(charsRemaining);
        text_counter.css('color', (charsRemaining < 0) ? 'red' : 'black');
      });

      $("#page_fb_description").keyup(function() {
        var description_counter = $("#description_counter");
        var charsRemaining = 200 - $(this).val().length;
        description_counter.text(charsRemaining);
        descrption_counter.css('color', (charsRemaining < 0) ? 'red' : 'black');
      });
 
    });
 </script>
<% end %>

<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :background_image %><br>
    <%= f.text_field :background_image %>
  </div>
  <div class="field">
    <%= f.label "Facebook ad headline (25 characters)" %><br>
    <%= f.text_area :fb_headline %>
    <div id="headline_counter">25</div>
  </div>
  <div class="field">
    <%= f.label "Facebook ad text (90 characters)" %><br>
    <%= f.text_area :fb_text %>
    <div id="text_counter">90</div>
  </div>
  <div class="field">
    <%= f.label "Facebook ad newsfeed link description (200 characters)" %><br>
    <%= f.text_area :fb_description %>
    <div id="description_counter">200</div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<p># subscribed fans: <%= @page.fans.count %></p>
<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th># Subscribed fans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @band.pages.each do |page| %>
      <tr>
        <td><%= page.name %></td>
        <td><%= truncate(page.description.html_safe, length: 65) %></td>
        <td><%= page.fans.count %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<!--<p id="notice"><%= notice %></p>-->


<div class="background" style="background-image: url(<%= @page.background_image %>)">

<div class="logo">
		<img src="<%= @band.logo %>">
</div>

		
<div class="signup">
	<h1>Get a free track</h1>

  <div>
      <%= form_for(@fan) do |f| %>
        <%= f.text_field :email, { :class => "email", :placeholder => "your email address" } %>
        <%=f.hidden_field :page_id, :value => @page.id %>
        <%= f.submit "DOWNLOAD", :class => "button" %>
      <% end %>
  </div>
</div>

<div class="content">
	<%=raw @page.description %>
</div>