config/routes.rb
Rails.application.routes.draw do
  resources :sales_pages
  resources :fans

  devise_for :admins
  resources :bands do
    resources :fans
    resources :pages, controller: 'bands/pages'
  end

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/confirm'
  get 'static_pages/thanks'
  get 'static_pages/free_download'
  get 'static_pages/youareahero'

   get '/confirm', to: "static_pages#confirm" 
   get '/thanks', to: "static_pages#thanks"
   get '/youareahero', to: "static_pages#youareahero", name: :youareahero
  resources :pages

  
  get '/music', to: "sales_pages#show"
  post '/music', to: "sales_pages#done"
  get '/:id', to: "pages#show"
 

end

app/models/fan.rb
class Fan < ActiveRecord::Base
	belongs_to :page
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  before_action :set_fan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:create]

  #CRUD for fans, except on creating a fan. On creation the fan is subscribed to a Mailchimp list

  # GET /fans
  # GET /fans.json
  def index
    @fans = Fan.all
  end

  # GET /fans/1
  # GET /fans/1.json
  def show
  end

  # GET /fans/new
  def new
    @fan = Fan.new
  end

  # GET /fans/1/edit
  def edit
  end

  # POST /fans
  # POST /fans.json
  def create
    @fan = Fan.new(fan_params)
    @email = @fan.email
    @page_name = @fan.page.name

    respond_to do |format|
      if @fan.save
        format.html { redirect_to thanks_path }
        format.json { render :show, status: :created, location: @fan }
        Mailchimp.lists.subscribe(@band.mailchimp_list, {:email => @email}, {'source' => @page_name }, 'html', true, true)
      else
        format.html {
          flash[:danger] = "This is not a valid email address"
          redirect_to :back }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fans/1
  # PATCH/PUT /fans/1.json
  def update
    respond_to do |format|
      if @fan.update(fan_params)
        format.html { redirect_to @fan, notice: 'Fan was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan }
      else
        format.html { render :edit }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fans/1
  # DELETE /fans/1.json
  def destroy
    @fan.destroy
    respond_to do |format|
      format.html { redirect_to fans_url, notice: 'Fan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan
      @fan = Fan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_params
      params.require(:fan).permit(:email, :page_id)
    end
end

app/helpers/fans_helper.rb
module FansHelper
end

app/views/fans/_form.html.erb
<%= form_for(@fan) do |f| %>
  <% if @fan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fan.errors.count, "error") %> prohibited this fan from being saved:</h2>

      <ul>
      <% @fan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fans/edit.html.erb
<h1>Editing fan</h1>

<%= render 'form' %>

<%= link_to 'Show', @fan %> |
<%= link_to 'Back', fans_path %>

app/views/fans/index.html.erb
<h1>Listing fans</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fans.each do |fan| %>
      <tr>
        <td><%= fan.email %></td>
        <td><%= link_to 'Show', fan %></td>
        <td><%= link_to 'Edit', edit_fan_path(fan) %></td>
        <td><%= link_to 'Destroy', fan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Fan', new_fan_path %>

<br><%= link_to 'Sign out', destroy_admin_session_path, :method => :delete %>

app/views/fans/new.html.erb
<h1>New fan</h1>

<%= render 'form' %>

<%= link_to 'Back', fans_path %>

app/views/fans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @fan.email %>
</p>

<%= link_to 'Edit', edit_fan_path(@fan) %> |
<%= link_to 'Back', fans_path %>