config/routes.rb
Rails.application.routes.draw do
  resources :sales_pages
  resources :fans

  devise_for :admins
  resources :bands do
    resources :fans
    resources :pages, controller: 'bands/pages'
  end

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/confirm'
  get 'static_pages/thanks'
  get 'static_pages/free_download'
  get 'static_pages/youareahero'

   get '/confirm', to: "static_pages#confirm" 
   get '/thanks', to: "static_pages#thanks"
   get '/youareahero', to: "static_pages#youareahero", name: :youareahero
  resources :pages

  
  get '/music', to: "sales_pages#show"
  post '/music', to: "sales_pages#done"
  get '/:id', to: "pages#show"
 

end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :pages
end

app/controllers/bands/pages_controller.rb
class Bands::PagesController < ApplicationController
  before_action :authenticate_admin!

  #CRUD for landing pages for each band. Made with scaffold

	def index
		@band = Band.find(params[:band_id])
	end

	def new
		band = Band.find(params[:band_id])
		@page = band.pages.build
  end

	def edit
		band = Band.find(params[:band_id])
    @page = Page.find_by(name: params[:id], band_id: band.id)
	end

	def create
    band = Band.find(params[:band_id])
    @page = band.pages.build(page_params)
    respond_to do |format|
      if @page.save
        format.html { redirect_to band_pages_path(band), notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
     band = Band.find(params[:band_id])
     @page = Page.find_by(name: params[:id], band_id: band.id)
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to band_pages_path(band), notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    band = Band.find(params[:band_id])
    @page = Page.find_by(name: params[:id], band_id: band.id)
    @page.destroy
    respond_to do |format|
      format.html { redirect_to band_pages_path(band), notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    def set_page
      #@page = Page.friendly.find(params[:id])
      #@page = Page.find_by(name: params[:id], band_id: @band.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :description, :background_image, :band_id, :fb_headline, :fb_text, :fb_description)
    end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	before_action :authenticate_admin!

	#CRUD for bands with a scaffold

	def index
		@bands = Band.all
	end

	def show
		@band = Band.find(params[:id])
	end

	def new
		@band = Band.new
	end

	def edit
		@band = Band.find(params[:id])
	end

	def create
		@band = Band.new(band_params)

		respond_to do |format|
			if @band.save
				format.html { redirect_to bands_path, notice: 'Band was succesfully created'}
			else
				format.html { render :new}
			end
		end
	end

	def update
		@band = Band.find(params[:id])
		respond_to do |format|
			if @band.update(band_params)
				format.html { redirect_to bands_path, notice: 'Band was succesfully updated'}
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@band.destroy
		respond_to do |format|
			format.html { redirect_to to bands_url, notice: 'Band was succesfully destroyed' }
		end
	end

	private

	def set_band
		@band = Band.find(params[:id])
	end

	def band_params
		params.require(:band).permit(:name, :short_name, :tumblr, :logo, :background_image, :host, :mailchimp_list, :mailchimp_buyers_list, :soundcloud_playlist, :facebook_conversion_code, :google_analytics_id, :mp3_download_link, :wav_download_link, :free_download_link, :facebook_page)
	end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%=f.label :name %>
		<%=f.text_field :name %>
	</div>
	<div class="field">
		<%=f.label :short_name, 'short name' %>
		<%=f.text_field :short_name %>
	</div>
	<div class="field">
		<%=f.label :tumblr %>
		<%=f.text_field :tumblr %>
	</div>
	<div class="field">
		<%=f.label :logo %>
		<%=f.text_field :logo %>
	</div>
	<div class="field">
		<%=f.label :background_image, "background image" %>
		<%=f.text_field :background_image %>
	</div>
	<div class="field">
		<%=f.label :host %>
		<%=f.text_field :host %>
	</div>
	<div class="field">
		<%=f.label :mailchimp_list, "Mailchimp leads list" %>
		<%=f.text_field :mailchimp_list %>
	</div>
	<div class="field">
		<%=f.label :mailchimp_buyers_list, "Mailchimp buyers list" %>
		<%=f.text_field :mailchimp_buyers_list %>
	</div>
	<div class="field">
		<%=f.label :soundcloud_playlist, "Soundcloud playlist" %>
		<%=f.text_field :soundcloud_playlist %>
	</div>
	<div class="field">
		<%=f.label :facebook_conversion_code, "Facebook conversion code" %>
		<%=f.text_area :facebook_conversion_code %>
	</div>
	<div class="field">
		<%=f.label :google_analytics_id, "Google Analytics id" %>
		<%=f.text_field :google_analytics_id %>
	</div>
	<div class="field">
		<%=f.label :mp3_download_link %>
		<%=f.text_field :mp3_download_link %>
	</div>
	<div class="field">
		<%=f.label :wav_download_link %>
		<%=f.text_field :wav_download_link %>
	</div>
	<div class="field">
		<%=f.label :free_download_link %>
		<%=f.text_field :free_download_link %>
	</div>
	<div class="field">
		<%=f.label :facebook_page %>
		<%=f.text_field :facebook_page %>
	</div>		

	<div class="actions">
		<%=f.submit %>
	</div>
<% end %>

app/views/bands/edit.html.erb
<h1>Edit band: <%= @band.name %> </h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<h1>Bands overview</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= link_to 'See Pages', band_pages_path(band) %>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>