config/routes.rb
Rails.application.routes.draw do
  resources :sales_pages
  resources :fans

  devise_for :admins
  resources :bands do
    resources :fans
    resources :pages, controller: 'bands/pages'
  end

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/confirm'
  get 'static_pages/thanks'
  get 'static_pages/free_download'
  get 'static_pages/youareahero'

   get '/confirm', to: "static_pages#confirm" 
   get '/thanks', to: "static_pages#thanks"
   get '/youareahero', to: "static_pages#youareahero", name: :youareahero
  resources :pages

  
  get '/music', to: "sales_pages#show"
  post '/music', to: "sales_pages#done"
  get '/:id', to: "pages#show"
 

end

app/models/sales_page.rb
class SalesPage < ActiveRecord::Base
end

app/controllers/sales_pages_controller.rb
class SalesPagesController < ApplicationController
   before_action :authenticate_admin!, except: [:show, :done]

  respond_to :html

  #A very short cut to setting up a quick payment page with Stripe
  #Very bad practice to reveal my Stripe api key :-o

  def show
    respond_with(@sales_page)
  end

  def edit
  end

  def done
  	#This part contains Stripe example comments...
  	#The app goes over here when the Stripe form is sent

    # Set your secret key: remember to change this to your live secret key in production
    # See your keys here https://dashboard.stripe.com/account/apikeys
    Stripe.api_key = "sk_live_LJJcNxFy0wBK0ii86hpjUGnr"

    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create the charge on Stripe's servers - this will charge the user's card

    #The user is charged € 3,95 over here

    begin
      charge = Stripe::Charge.create(
        :amount => "0395", # amount in cents, again
        :currency => "eur",
        :source => token,
        :description => @band.name
      )
    rescue Stripe::CardError => e
      # The card has been declined
      # I didn't implement anything for errors....
    end
    #The user is redirect to the static thanks page
    redirect_to thanks_url
    #The user is subscribed to a different buyers list via the Mailchimp API
    email = params[:stripeEmail]
    source = params[:utm_source]
    Mailchimp.lists.subscribe(@band.mailchimp_buyers_list, {:email => email}, {'source' => source }, 'html', true, true)

  end

  private

    def sales_page_params
      params.require(:sales_page).permit(:name, :background_image, :soundcloud, :buy_button)
    end
end

app/helpers/sales_pages_helper.rb
module SalesPagesHelper
end

app/views/sales_pages/_form.html.erb
<%= form_for(@sales_page) do |f| %>
  <% if @sales_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_page.errors.count, "error") %> prohibited this sales_page from being saved:</h2>

      <ul>
      <% @sales_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :background_image %><br>
    <%= f.text_field :background_image %>
  </div>
  <div class="field">
    <%= f.label :soundcloud %><br>
    <%= f.text_area :soundcloud %>
  </div>
  <div class="field">
    <%= f.label :buy_button %><br>
    <%= f.text_area :buy_button %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_pages/edit.html.erb
<h1>Editing sales_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_page %> |
<%= link_to 'Back', sales_pages_path %>

app/views/sales_pages/index.html.erb
<h1>Listing sales_pages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Background image</th>
      <th>Soundcloud</th>
      <th>Buy button</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_pages.each do |sales_page| %>
      <tr>
        <td><%= sales_page.name %></td>
        <td><%= sales_page.background_image %></td>
        <td><%= sales_page.soundcloud %></td>
        <td><%= sales_page.buy_button %></td>
        <td><%= link_to 'Show', sales_page %></td>
        <td><%= link_to 'Edit', edit_sales_page_path(sales_page) %></td>
        <td><%= link_to 'Destroy', sales_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sales page', new_sales_page_path %>

app/views/sales_pages/new.html.erb
<h1>New sales_page</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_pages_path %>

app/views/sales_pages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="background" style="background-image: url(<%= @band.background_image %>)">

<div class="logo">
		<img src="<%= @band.logo %>">
</div>

<div class="content wider_content">

  <h1>Discover our music</h1>
  <p class="soundcloud">
    <!-- band soundcloud -->
    <iframe width="400" height="250" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<%= @band.soundcloud_playlist %>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
  </p>

  <p class="buy">
  <!-- band buy button -->
  	Wanna buy?
    <form action="" method="POST">
    	<%= token_tag(nil) %>
    	<%= hidden_field_tag :utm_source, params[:utm_source] %>
	  <script
	    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	    data-key="pk_live_RXe6VAu54lL4SGyo0jyaGtQb"
	    data-currency="eur"
      data-amount="0395"      
	    data-name="<%= @band.name %>"
	    data-description="<%= @band.name %> EP"
	    data-image="<%= @band.logo %>">
	  </script>
	</form>

	<!-- Stripe test key is data-key="pk_test_pGmDYpUdPOCikVJO7Fh3NIMc"
  live key: pk_live_RXe6VAu54lL4SGyo0jyaGtQb
  -->
  </p>
</div>
</div>